#!/bin/bash

# FZF
export FZF_DEFAULT_COMMAND="fdfind --type f --follow --exclude .git"
export FZF_DEFAULT_OPTS="--height 40% --layout=reverse --border"
export FZF_CTRL_T_COMMAND="fdfind --type f --hidden --follow --exclude .git"

