#!/bin/bash



# clip
alias clip='xclip -sel clip'

# fd-find
alias fd='fdfind'
alias fp="fzf -m --preview 'batcat --style=numbers --color=always {} | head -500'"

# git
alias gst='git status'
alias ga='git add'
alias gpush='git push'

# kiali
alias kiali="${HOME}/Documents/git/linux/scripts/utilities/kiali/kiali.sh"

# kubernetes
alias k='kubectl'
