#!/bin/bash

# Shorthand k for kubectl
source <(kubectl completion bash)

alias k='kubectl'
complete -F __start_kubectl k

# fd-find
alias fd='fdfind'

# FZF
export FZF_DEFAULT_COMMAND="fdfind --type f --follow --exclude .git"
export FZF_DEFAULT_OPTS="--height 40% --layout=reverse --border"
export FZF_CTRL_T_COMMAND="fdfind --type f --hidden --follow --exclude .git"

alias fp="fzf -m --preview 'batcat --style=numbers --color=always {} | head -500'"

# git
alias gst='git status'
alias ga='git add'
alias gpush='git push'