#!/bin/bash

POD_NAME="${1}"
CLUSTER="${2}"
NAMESPACE="${3}"

if [ -z "${CLUSTER?}"]; then
  echo "[INFO] Choose k8s cluster..."
  CLUSTER=$(kubectl config get-contexts | sed '1d' | awk '{ print $2 }' | sort | fzf)
fi

if [ -z "${NAMESPACE?}"]; then
  echo "[INFO] Choose Namespace..."
  NAMESPACE=$(kubectl get namespaces --context ${CLUSTER} | sed '1d' | awk '{ print $1 }' | fzf)
fi

echo "[INFO] Choose Pod..."
POD_NAME=$(kubectl get pod --context ${CLUSTER} --namespace ${NAMESPACE} | sed '1d' | awk '{ print $1 }' | grep -E "${POD_NAME}" | fzf)

echo "[INFO] Choose ENV VAR..."
ENV_VAR=$(kubectl exec $POD_NAME --context ${CLUSTER} --namespace ${NAMESPACE} -- env | fzf)
echo "ENV_VAR.....: $ENV_VAR"